restore BR on python-eventlet
thus fixing build failure:

--- import errors ---
Failed to import test module: os_xenapi.tests.client.test_session
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/unittest2/loader.py", line 445, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/site-packages/unittest2/loader.py", line 384, in _get_module_from_name
    __import__(name)
  File "/builddir/build/BUILD/os-xenapi-0.1.2.dev26/os_xenapi/tests/client/test_session.py", line 22, in <module>
    from os_xenapi.client import session
  File "/builddir/build/BUILD/os-xenapi-0.1.2.dev26/os_xenapi/client/session.py", line 27, in <module>
    from eventlet import queue
ImportError: No module named eventlet

Change-Id: I91502dede2d73bfe4a8aab316d1726193a1dab75